### ISSUE TITLE
Another Transparency Issue

### ISSUE THREAD

**Issue by Zet4Dragon** [AlexFlipnote/Discord_Theme#100]
Transparency not being applied when a user is typing.
![image](https://user-images.githubusercontent.com/26089350/34537192-942be714-f0bf-11e7-90af-1cc9f614282b.png)

**Comment by AlexFlipnote** [comment]
Update to the latest version of the theme, this was fixed here:
![Image](https://i.alexflipnote.xyz/45ceaa.png)
