### ISSUE TITLE
Overlapping "Now Typing"

### ISSUE THREAD

**Issue by BlackLotusLV** [AlexFlipnote/Discord_Theme#101]
The thing that shows who is typing is overlapping the text box. Cant see what i'm writing then.
![example](https://user-images.githubusercontent.com/20668065/34650890-e35f28fa-f3d0-11e7-8e57-ea8c816f5a0d.png)

**Comment by DudeVoid** [comment]
Patched in latest update.

**Comment by DudeVoid** [comment]
Are you on regular Discord or Canary Discord?

**Comment by BlackLotusLV** [comment]
PTB, And using the auto theme. I assume it works properly on Canary then?

**Comment by DudeVoid** [comment]
Yeah.

**Comment by DudeVoid** [comment]
Download Canary and apply the theme, should be back to normal.

**Comment by BlackLotusLV** [comment]
Will do ;)
cheers mate.

**Comment by AlexFlipnote** [comment]
This update was patched in the Canary update, it's documented that I always keep it up-to-date to that Discord version here:
![Image](https://i.alexflipnote.xyz/6a8e6a.png)

Regardless, thanks for keeping an eye out for bugs, I really like people like you around my theme development. ❤️
