### ISSUE TITLE
Transparency issue - color issue

### ISSUE THREAD

**Issue by BlackLotusLV** [AlexFlipnote/Discord_Theme#103]
The channel info bar isn't transparent and the unread channels show up as purple.

**Comment by AlexFlipnote** [comment]
I'll check with transparent thing, however with the unread message as purple, it isn't a bug.
You can change this colour however, by adding this code into your theme:
```css
:root {
  --accent: #HEX;
}
```

![Image](https://i.alexflipnote.xyz/2949fb.png)

It's noted in the documentation that you can change colours to a lot of the stuff in the theme.
Regardless, I will fix the transparent at least.

**Comment by AlexFlipnote** [comment]
Forgot to tell, here is an example when you change the colour:

![Image](https://i.alexflipnote.xyz/d8854e.png)

**Comment by BlackLotusLV** [comment]
Yes, sorry for mistaking that color thing for a bug, just was used to having it white and now today it turned to purple :D 
Thanks ;)

**Comment by AlexFlipnote** [comment]
# Update | 11:27 GMT +1, 23/01/2018
The title bar is fixed, however I will spend some more time trying to make it more readable around channel names and such 

![Image](https://i.alexflipnote.xyz/d72954.png)

**Comment by AlexFlipnote** [comment]
# Issue solved
Patch has been published 👌 

![Image](https://i.alexflipnote.xyz/0233e1.png)
