### ISSUE TITLE
[minor] when i hover over channels there is a slight color change

### ISSUE THREAD

**Issue by atte7** [AlexFlipnote/Discord_Theme#111]
hi, not sure how to explain this but whenever i hover over channels certain colors change
![2018-05-09_02-13-52](https://user-images.githubusercontent.com/39105447/39787678-3723b3a8-532f-11e8-9665-bbd3093ceffa.gif)
(look at the names and link)
not sure if this is intended, if it is could you please tell me how to disable it
thanks !

**Comment by perryprog** [comment]
I cannot reproduce this, can you give some system details and any custom css you have on top of the default theme?

**Comment by atte7** [comment]
seems to be a problem with windows 10 cleartype, works fine with it disabled
sorry to waste your guys time

**Comment by perryprog** [comment]
Don't worry, you haven't wasted anyone's time.
