### ISSUE TITLE
NSFW screen broken

### ISSUE THREAD

**Issue by Bowser65** [AlexFlipnote/Discord_Theme#117]
https://cdn.bowser65.tk/s/NaniEUfQ.png

**Comment by AlexFlipnote** [comment]
Will fix it, I rarely check nsfw channels so I never knew it was a bug, lmao

**Comment by AlexFlipnote** [comment]
This has now been solved, will come out as an update soon.

![Image](https://i.alexflipnote.xyz/cad87d.png)
