### ISSUE TITLE
Discord Theme - BetterDocs - [Issue Report]

### ISSUE THREAD

**Issue by Jashanlol** [AlexFlipnote/Discord_Theme#127]
Please fix typing status where it says "@user is typing" or "several people are typing" because it blocks the last message from being read

**Comment by AlexFlipnote** [comment]
Are you sure it blocks the last message? It seems to work fine for me right here.

![Image](https://i.alexflipnote.dev/3TdFKXX.gif)

**Comment by martmists** [comment]
This seems to happen on non-standard zoom levels and/or text sizes, can confirm.

**Comment by AlexFlipnote** [comment]
Even if you zoom and so, it still works just fine for me 
![image](https://i.alexflipnote.dev/8UL7qDe.png)
