### ISSUE TITLE
Issue with colors of some parts

### ISSUE THREAD

**Issue by krzychumagiczny** [AlexFlipnote/Discord_Theme#142]
there is an issue with coloring of channel list and channel name part, they have default discord colors
![Bez tytułu](https://user-images.githubusercontent.com/62946030/78034381-f2c45400-7367-11ea-8fab-d5d704247d42.png)

**Comment by AlexFlipnote** [comment]
Are you using Discord Canary?

**Comment by BloodDragooner** [comment]
> 
> 
> Are you using Discord Canary?

Not the original poster, but I am also having this same issue on PTB, unsure why

**Comment by AlexFlipnote** [comment]
It's because the theme is updated to stay with the latest Canary, as shown [here](https://github.com/AlexFlipnote/Discord_Theme/blob/master/docs/Documentation.md#discord-version). Here's how it looks for me atm, updated Discord recently too.

![](https://i.alexflipnote.dev/8FyZZ8z.png)

**Comment by BloodDragooner** [comment]
Cheers Alex! Thanks! Hope the original poster sees this as well

**Comment by krzychumagiczny** [comment]
I'm using stable Discord version, but now everything's fine, so i'll be closing this thread now
