### ISSUE TITLE
Weird background in transparent GIF embeds

### ISSUE THREAD

**Issue by BlackOfWorld** [AlexFlipnote/Discord_Theme#143]
Hey,

For some reason (I think I know why, but I'm not a webdev lmao), [this](https://github.com/AlexFlipnote/Discord_Theme/blob/3665bdb4ed79f3def71c8f789035af4982e6bb78/scss/components/_chat.scss#L345) it causing GIFs background to be black and not transparent.

With background-color:
![](https://i.imgur.com/j90m83i.png)
Without background-color: 
![](https://i.imgur.com/q8Lykju.png)

**Comment by AlexFlipnote** [comment]
Yeah I haven't touched this theme for like months, so I haven't been fixing anything these days.
Been getting work as well so I haven't found any time to update it + I don't use my own theme anymore, lol.

**Comment by BlackOfWorld** [comment]
I can make pull request and you can merge it, if you don't really don't wanna touch it ❤️  I'm closing this since you responded :)
