### ISSUE TITLE
"Discord partner" icon is misplaced

### ISSUE THREAD

**Issue by charlesmilette** [AlexFlipnote/Discord_Theme#20]
Regular:
![image](https://cloud.githubusercontent.com/assets/6440374/24066543/0801bd96-0b4a-11e7-9f83-ce0277bd668a.png)

With theme:
![image](https://cloud.githubusercontent.com/assets/6440374/24066634/a47e7128-0b4a-11e7-82cf-1abb2db718f6.png)

Applying the same styling than nitro but with different size, position and margin properties (because the partner icon is bigger in both width and height) seems to be working.

**Comment by AlexFlipnote** [comment]
Oh, I haven't noticed that, I will fix that tomorrow when I have the time.
Currently it's 00:49 and a bit late here in Norway

Thanks for the Issue, this will be solved 👌

**Comment by Bowser65** [comment]
Discord Staff icon has the same issue ^^

![DiscordStaff icon issue](https://cloud.githubusercontent.com/assets/9999055/24067237/247fc42e-0b7a-11e7-8d51-770451124420.png)

**Comment by AlexFlipnote** [comment]
Indeed, both Partner and Staff have the same target, so it should be easy solvable

**Comment by AlexFlipnote** [comment]
This has now been solved, will be releasing the update right now.
Thanks again for helping the theme become better 👌 

<img src="https://i.alexflipnote.xyz/03188Bh.png">
<img src="https://i.alexflipnote.xyz/0318vUs.png">
