### ISSUE TITLE
White Input Boxes

### ISSUE THREAD

**Issue by deatcoca** [AlexFlipnote/Discord_Theme#23]
I updated the theme today and now every "input boxes" where you can input text render pretty weirdly, see pictures. 

![0_01 25 40](https://cloud.githubusercontent.com/assets/24621065/24317715/7f9abc58-10fa-11e7-8af0-d8398c041195.png)
![9_01 25 06](https://cloud.githubusercontent.com/assets/24621065/24317716/7fa059c4-10fa-11e7-9851-e8b76f5a509a.png)

I don't know if you are already aware of this so I'm posting it here. Thank you for creating this very nice theme by the way !

**Comment by Bowser65** [comment]
It's because the latest update was made for Discord Canary (Beta of Discord) ^^

![capture](https://cloud.githubusercontent.com/assets/9999055/24317845/c0efbc38-10fc-11e7-842c-bcd21e69c7a9.png)

**Comment by ThePoolQueen** [comment]
It's probably gonna be a while till we see these menus hit the main build, but the theme has already moved towards Canary features, including a rewrite of the theme.

![discordcanary_2017-03-25_01-50-14](https://cloud.githubusercontent.com/assets/22428156/24317900/84b6d8fe-10fd-11e7-903d-795798a6b3e9.png)

**Comment by deatcoca** [comment]
Oh okay, thank you guys for the info. I'll try to switch to canary :smile:

**Comment by AlexFlipnote** [comment]
if I can state my comment on here, this is actually broken on Canary as well, since I use it myself..
We are currently doing a rewrite, so this issue should be solved in a short time

**Comment by deatcoca** [comment]
Okay, thank you very much Alex!

**Comment by Rxswyers** [comment]
It's fixed as of now :wink:
