### ISSUE TITLE
"Discord HypeSquad Member" icon is misplaced

### ISSUE THREAD

**Issue by deatcoca** [AlexFlipnote/Discord_Theme#24]
I don't know what a Discord "HypeSquad Member" is, but their icon is also misplaced with the theme. Just like "Discord Partner" and "Staff Member" before the fix.
![5_18 46 05](https://cloud.githubusercontent.com/assets/24621065/24333317/09cbdd24-1256-11e7-9eca-cc6b5e2dba9e.png)
Nothing really important but I just wanted to let you know.

**Comment by AlexFlipnote** [comment]
is there a possibility that you can invite me to a server where he is? I need to see what code that badge has

**Comment by AlexFlipnote** [comment]
Alright, this has been fixed in the rewrite, expect the fix to come soon!
https://github.com/AlexFlipnote/Discord_Theme/commit/f541cda3ace7792799405fa505a027589cf0247d
