### ISSUE TITLE
Server's with really long names that wrap around in the emoji picker break it.

### ISSUE THREAD

**Issue by Ovyerus** [AlexFlipnote/Discord_Theme#31]
![image](https://all.foxgirlsare.sexy/7cfa39.png)

**Comment by AlexFlipnote** [comment]
My question is.. why do you have servers with so long names at the first place, lol

**Comment by Ovyerus** [comment]
TBH I don't know why I'm still there. heh

**Comment by AlexFlipnote** [comment]
I might disclose it due to that having long names like that is incredibly rare.

**Comment by PikaDude** [comment]
isn't that a discord bug?

**Comment by Ovyerus** [comment]
Removed theme, seems like it is.

**Comment by AlexFlipnote** [comment]
Yeah, then I'll close this issue due to that this is an issue i can't resolve, sorry.
