### ISSUE TITLE
The NEW MESSAGES and date can overlap

### ISSUE THREAD

**Issue by martmists** [AlexFlipnote/Discord_Theme#33]
![Image](https://light-theme-hurts.my-ey.es/fe859d.png)

When this theme is disabled (i.e. using default theme), the date is not displayed until the `NEW MESSAGES` has disappeared.

**Comment by ThePoolQueen** [comment]
This is not an issue that can be fixed simply with a code in the theme since you're disabling and enabling the theme, the best you could complain to is BeautifulDiscord, but I doubt that'll get you far. The best recommendation I have is "CTRL + R" Discord.

**Comment by Rxswyers** [comment]
Was most def a bug with our theme, just pushed a fix! Thanks for the bug report :wink:
