### ISSUE TITLE
A broken image in Documentation.md

### ISSUE THREAD

**Issue by MDMCK10** [AlexFlipnote/Discord_Theme#50]
[This image](https://camo.githubusercontent.com/0b10343876606c8816376681b86e918aa1185292/68747470733a2f2f692e616c6578666c69706e6f74652e78797a2f303330327332552e706e67) appears to be broken in the [Docs](https://github.com/AlexFlipnote/Discord_Theme/blob/master/Documentation.md) page

It seems to 403

**Comment by AlexFlipnote** [comment]
Ah, I see which image, will solve it

**Comment by AlexFlipnote** [comment]
This has been solved in aca5240
Thank you for the issue report
