### ISSUE TITLE
Pins go too far out

### ISSUE THREAD

**Issue by tilda** [AlexFlipnote/Discord_Theme#68]
![image](https://user-images.githubusercontent.com/8301262/28955668-c4d6c4ae-78ad-11e7-8fe0-430fa61ff7b3.png)
This is with the normal theme (I disabled the plugins to verify this)

Steps to reproduce:

-  Pin a message

- Click the little link in the message that shows up when you pin things twice

- Everything looks weird now.

**Comment by AlexFlipnote** [comment]
Well shit.. I'll look into it

**Comment by AlexFlipnote** [comment]
day 11.. still can't find how to fix this...

**Comment by tilda** [comment]
rip
