### ISSUE TITLE
There is a problem with the typing box in transparent.css

### ISSUE THREAD

**Issue by aaether32323** [AlexFlipnote/Discord_Theme#69]
![beautifuldiscord](https://user-images.githubusercontent.com/29077900/29142075-b5b98d74-7d1e-11e7-98c5-f6a8239f5b3e.png)

It has a darker color than the rest of the app. I fixed it by changing the position of `.chat form .typing`.
The fixed file is [here.](https://pastebin.com/yx5UM7nT)

**Comment by AlexFlipnote** [comment]
Sorry for the late response, this should be fixed now
