### ISSUE TITLE
button misplacement

### ISSUE THREAD

**Issue by notoriouskyoko** [AlexFlipnote/Discord_Theme#74]
when discord added video chat to nitro users it borked the theme.

https://kyoko.is-going-to.space/430912.png

pls fix alex

**Comment by AlexFlipnote** [comment]
Already aware of it

**Comment by notoriouskyoko** [comment]
it has been 10 days still not fixed and still ignores me reee

**Comment by AlexFlipnote** [comment]
and I still haven't found a way to solve this
