### ISSUE TITLE
another possibly broken image in README

### ISSUE THREAD

**Issue by MDMCK10** [AlexFlipnote/Discord_Theme#79]
[this](https://camo.githubusercontent.com/1c241e845770f63aec76a667ec8a5b9bc7caffc8/68747470733a2f2f692e6d6966792e70772f3734353861312e706e67) image appears to be broken in the README, when clicked, it just shows a page with the error "Cannot proxy the given URL".

**Comment by notoriouskyoko** [comment]
what image?

**Comment by MDMCK10** [comment]
this was fixed in [0792c5c ]https://github.com/AlexFlipnote/Discord_Theme/commit/5d5ef388c4dbe0d5e5c7518b4d1fb30342621e4a

**Comment by AlexFlipnote** [comment]
mfw just noticed the issue now so I fixed it without being aware

I call hax

**Comment by MDMCK10** [comment]
🤔
