### ISSUE TITLE
Offset borders

### ISSUE THREAD

**Issue by mcao** [AlexFlipnote/Discord_Theme#81]
There is a slight offset between the user bar and the message bar. Is this supposed to be there, or is it a bug?
https://asianboi.got-lost-in.space/9fb98b.png
https://b1nzy.took-my-blobs-away-from.me/fe87fa.png

**Comment by AlexFlipnote** [comment]
I will look into it

**Comment by AlexFlipnote** [comment]
It runs perfectly fine for me
![Image](https://i.alexflipnote.xyz/8e981b.png)

Are you sure you've not edited something?

**Comment by mcao** [comment]
No, I'm importing your theme directly from the repo.

**Comment by martmists** [comment]
Please add zoom level, text size and resolution so we can try to accurately reproduce the error

**Comment by mcao** [comment]
Chat font scaling: 110
Zoom Level: 90
Resolution: 1440 x 900

**Comment by AlexFlipnote** [comment]
Yeah, now I got the same issue too.

**Comment by mcao** [comment]
It's due to the chat font scaling - it only appears when I change that setting.

**Comment by AlexFlipnote** [comment]
Problem is, I won't really solve it just because of the zoom being customized, as I work for the default settings. However, I can provide you a snippet to fix it locally for your own view:
```css
.theme-dark .channel-text-area-default div[class*="inner-"] {
    padding-top: 5px;
}
```

5px is the default one, try to set it for 4px and see if that helps for you

**Comment by mcao** [comment]
It works. Thanks!
