### ISSUE TITLE
Message bar disappearing below the window

### ISSUE THREAD

**Issue by Tobotimus** [AlexFlipnote/Discord_Theme#85]
After some recent updates, the message bar is disappearing below the window as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/7438501/31748802-71a2fdde-b4c1-11e7-96cb-f83040e7dac2.png)

Typing brings the bar back up slightly but not fully:
![image](https://user-images.githubusercontent.com/7438501/31748831-9668405c-b4c1-11e7-968f-24fb630cda93.png)

I'm on Discord's latest release (not Canary), zoom level is 100, chat font scaling 100, resolution 1920x1080.

**Comment by AlexFlipnote** [comment]
I'll fix it when I get time, around an hour

**Comment by AlexFlipnote** [comment]
✅ This is solved

Reference: 58d157a
