### ISSUE TITLE
Text box goes lower than normal

### ISSUE THREAD

**Issue by Takeoverkyle** [AlexFlipnote/Discord_Theme#86]
Noticed after today's Canary update that the text boxes (no matter the server) went lower than the settings tab I guess you could call it. Anyone else having this problem?
![1gzgmr2](https://user-images.githubusercontent.com/24795942/31845351-db9c6236-b5cd-11e7-99f4-eb8d3c39dcf0.png)
![2ckzaev](https://user-images.githubusercontent.com/24795942/31845352-dbaffa4e-b5cd-11e7-8368-7a4d09bcd5eb.png)

**Comment by Takeoverkyle** [comment]
Latest updates from Canary seemed to have fix this problem.

**Comment by AlexFlipnote** [comment]
oh, lol
