### ISSUE TITLE
Transparency Issue

### ISSUE THREAD

**Issue by Zet4Dragon** [AlexFlipnote/Discord_Theme#95]
Transparency break when in channels where the user doesn't have upload files permission.
![imagem](https://user-images.githubusercontent.com/26089350/33799285-735ce3ce-dd20-11e7-8fc9-d7f4bbc893fc.png)

**Comment by AlexFlipnote** [comment]
Will solve it right away

**Comment by AlexFlipnote** [comment]
This has been resolved, thank you for the report.
Please update your theme to have the fixed version.
