### ISSUE TITLE
Add installer for Unix-based systems

### ISSUE THREAD

**Issue by martmists** [AlexFlipnote/Discord_Theme#96]

**Comment by AlexFlipnote** [comment]
Was considering it actually, will start making it when I get a virtual machine running and so

**Comment by TheCyberRonin** [comment]
I think that would be pointless tbh. If people are running a Unix-based OS, they should be familiar with running a few commands. If you really wanted to, you could use a shell script, but it'd have to install Python 3.X when it will most likely come with Python 2.7. I'm unsure if it's across the board, but you may just run into issues using a bash script for Unix-based systems in general.

**Comment by AlexFlipnote** [comment]
That's quite true tbh, I might just drop the idea then.

**Comment by martmists** [comment]
A lot of apple users have no clue about using commands though

**Comment by martmists** [comment]
I'm gonna start working on this, and just set it to use python3 if installed, otherwise display an error.

**Comment by AlexFlipnote** [comment]
tbh, not sure if we really need it, as mentioned above, most are already known to the Linux world and commands in terminal
