### ISSUE TITLE
Keybinds Not Working

### ISSUE THREAD

**Issue by Zet4Dragon** [AlexFlipnote/Discord_Theme#99]
Able to add a new keybind but not setting the action. Edit Keybind button flickers while the mouse overs it.
![](https://i.imgur.com/5NwzYXZ.gif)

**Comment by AlexFlipnote** [comment]
Hmmm, I will have a look on that, thanks for sending the bug ❤️

**Comment by AlexFlipnote** [comment]
This has been resolved in commit 01b4bad :3
